name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Review the changes in this pull request for code quality, bugs, adherence to project standards. Provide inline comments or suggestions.
          claude_args: |
            --max-turns 5
            --model claude-sonnet-4-20250514